 # 1.  IMPORTING PANDAS

# 2. OPENING A LOCAL CSV

 # 3. OPENING A CSV FILE FROM AN URL

In [2]:
#  THROUGH THE SERVER SE KOI FILE

- requests.get() → downloads the raw CSV data from the URL.

- StringIO → acts like a file object, allowing pandas to read from the response text.

- pd.read_csv() → loads the CSV into a DataFrame.

- headers → mimic a browser request (sometimes needed for protected URLs).

In [5]:
import requests
import pandas as pd
from io import StringIO
# Example CSV URL
url = "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"
headers = {
    "User-Agent": "Mozilla/5.0"
}
# Fetch the data
response = requests.get(url, headers=headers)
# Convert response text into a StringIO object
csv_data = StringIO(response.text)
# Read CSV with pandas
df = pd.read_csv(csv_data)
df

     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]

 # 4.SEP PARMETER

In [8]:
pd.read_csv(r"C:\Users\HOME\Downloads\movie_titles_metadata.tsv",sep ="\t",names= ["serial_no.","movies_name","release_year","rating","votes","genres"])

,serial_no.,movies_name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [9]:
 # 5. INDEX_COL PARAMETER --> AGAR APKE PASS KOI COLUMN AI JO APKE KAAM NHI A SAKTA USE APP INDEX BNA SAKTE HO

In [11]:
pd.read_csv(r"C:\Users\HOME\Downloads\aug_train.csv",index_col ="enrollee_id")

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

 # 6. Header Parameter

 # working with excel file

In [6]:
import pandas as pd 
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [7]:
pd.read_excel(r"C:\Users\HOME\OneDrive\Desktop\dataset_download\marks.xlsx", index_col= 0 )

               MARKS  HOURS
SUBJECTS
physics           34      4
maths             22      5
matplotlib        23      6
chemistry         33      7
biology           33      8
seaborn           43      2
pandas            54      3
data analysis     67      4
data science      89      5
urdu              78      6
hindi             78      4

In [9]:
import pandas as pd

xls = pd.ExcelFile(r"C:\Users\HOME\OneDrive\Desktop\dataset_download\marks.xlsx")
print(xls.sheet_names)

['Sheet1', 'Sheet2']

In [13]:
# (Index starts from 0, so sheet_name=1 means the second sheet.)

df = pd.read_excel(r"C:\Users\HOME\OneDrive\Desktop\dataset_download\marks.xlsx", sheet_name=0)
df

        SUBJECTS   MARKS  HOURS
0         physics     34      4
1           maths     22      5
2      matplotlib     23      6
3       chemistry     33      7
4         biology     33      8
5         seaborn     43      2
6          pandas     54      3
7   data analysis     67      4
8    data science     89      5
9            urdu     78      6
10          hindi     78      4

In [16]:
df = pd.read_excel(r"C:\Users\HOME\OneDrive\Desktop\dataset_download\marks.xlsx", sheet_name=1)
df

  numpy pandas seaborn matplotlib              plotly
0    wb     wb      wb         wb          web design
1    dv     dv      dv         dv  data visualization
2    ds     ds      ds         ds       data science
3    ml     ml      ml         ml    machine learning

 # Reading text files

In [ ]:
pd.read_csv